#!/usr/bin/env python3

import urllib.request
import sys

try:
  response = urllib.request.urlopen('http://localhost:4567/api/health-check')
  if response.getcode() == 200:
    print("[OK] Flask server is running")
    sys.exit(0) # success
  else:
    print("[BAD] Flask server is not running")
    sys.exit(1) # false
# This for some reason is not capturing the error....
#except ConnectionRefusedError as e:
# so we'll just catch on all even though this is a bad practice
except Exception as e:
  print(e)
  sys.exit(1) # false